import type { Job, NavItem, FooterColumn } from '@/types';

export const navItems: NavItem[] = [
  { label: 'Web3 Jobs', href: '/', hasDropdown: false },
  { label: 'Partnerships', href: '/partnerships', hasDropdown: false },
  { label: 'Agents', href: '/agents', hasDropdown: false },
  { label: 'Salaries', href: '/salaries', hasDropdown: false },
  { label: 'Internships', href: '/internships', hasDropdown: false },
  { label: 'Learn Web3', href: '/learn', hasDropdown: false },
  { label: 'TOP Web3 Jobs', href: '/top-jobs', hasDropdown: false },
];

export const skillTags = [
  'ai', 'analyst', 'backend', 'bitcoin', 'blockchain', 'community manager', 'crypto', 
  'cryptography', 'cto', 'customer support', 'dao', 'data science', 'defi', 'design',
  'developer relations', 'devops', 'discord', 'economy designer', 'entry level', 'erc',
  'erc 20', 'evm', 'front end', 'full stack', 'gaming', 'ganache', 'golang', 'hardhat',
  'intern', 'java', 'javascript', 'layer 2', 'marketing', 'mobile', 'moderator', 'nft',
  'node', 'non tech', 'open source', 'openzeppelin', 'pay in crypto', 'product manager',
  'project manager', 'react', 'refi', 'research', 'ruby', 'rust', 'sales', 'smart contract',
  'solana', 'solidity', 'truffle', 'web3 py', 'web3js', 'zero knowledge'
];

export const jobs: Job[] = [
  {
    id: 1,
    title: 'Senior Blockchain Developer',
    company: 'Lemon.io',
    companyLogo: 'L',
    location: 'Canada, the U.S., LATAM, Europe, Asia, Oceania',
    salary: '$70k - $172k',
    salaryMin: 70000,
    salaryMax: 172000,
    tags: ['dev', 'senior', 'blockchain', 'angular', 'golang'],
    postedAt: '10h',
    isRemote: true,
    cardType: 'default',
    description: 'Are you a talented Senior Developer looking for a remote job that lets you showcase your skills and earn competitive compensation? Look no further than Lemon.io — the marketplace that connects you with hand-picked startups in the US and Europe.',
    offerings: [
      'The rate depends on your seniority level, skills and experience. We\'ve already paid out over $11M to our engineers.',
      'No more hunting for clients or negotiating rates — let us handle the business side of things so you can focus on what you do best.',
      'We\'ll manually find the best project for you according to your skills and preferences.',
      'Choose a schedule that works best for you. It\'s possible to communicate async or minimally overlap within team working hours.',
      'We respect your seniority so you can expect no micromanagement or screen trackers.',
      'Communicate directly with the clients. Most of them have technical backgrounds. Sounds good, yeah?',
      'We will support you from the time you submit the application throughout all cooperation.'
    ]
  },
  {
    id: 2,
    title: 'Web3 Solidity Bootcamp - Job Guaranteed',
    company: 'Metana',
    companyLogo: 'M',
    location: 'Remote',
    salary: '',
    tags: ['bootcamp', 'solidity', 'web3', 'job guarantee'],
    postedAt: '1d',
    isRemote: true,
    isFeatured: true,
    cardType: 'yellow',
    description: 'Learn job-ready web3 skills on your schedule with 1-on-1 support & get a job, or your money back.',
    offerings: [
      'Comprehensive Solidity curriculum',
      '1-on-1 mentorship from industry experts',
      'Job guarantee or money back',
      'Flexible learning schedule',
      'Portfolio projects'
    ]
  },
  {
    id: 3,
    title: 'Product Security Engineer',
    company: 'Hashgraph',
    companyLogo: 'H',
    location: 'Remote from within Europe',
    salary: '',
    tags: ['engineer', 'security', 'remote', 'aws', 'blockchain'],
    postedAt: '1d',
    isRemote: true,
    cardType: 'purple',
    description: 'Join our security team to help build and maintain secure blockchain infrastructure. You will be responsible for identifying vulnerabilities, implementing security measures, and ensuring the integrity of our distributed systems.',
    offerings: [
      'Competitive salary package',
      'Remote-first culture',
      'Professional development budget',
      'Health and wellness benefits',
      'Stock options'
    ]
  },
  {
    id: 4,
    title: 'Senior Software Engineer - Trading Infrastructure Team',
    company: 'Gravity Team',
    companyLogo: 'G',
    location: 'Riga, Amsterdam, Remote with frequent travel',
    salary: '',
    tags: ['infrastructure', 'engineer', 'senior', 'dev', 'api'],
    postedAt: '1d',
    isRemote: true,
    cardType: 'default',
    description: 'We are looking for a Senior Software Engineer to join our Trading Infrastructure Team. You will work on high-performance trading systems, optimizing latency and throughput for our crypto trading operations.',
    offerings: [
      'Work with cutting-edge trading technology',
      'Competitive compensation',
      'Travel opportunities',
      'Professional growth',
      'Collaborative team environment'
    ]
  },
  {
    id: 5,
    title: 'VP Engineering',
    company: 'Genius',
    companyLogo: 'G',
    location: 'Remote',
    salary: '$200k - $300k',
    salaryMin: 200000,
    salaryMax: 300000,
    tags: ['executive', 'remote', 'rust', 'solana', 'typescript'],
    postedAt: '2d',
    isRemote: true,
    cardType: 'purple',
    description: 'Lead our engineering team and drive technical strategy. We are building the next generation of decentralized applications on Solana and need an experienced leader to guide our engineering efforts.',
    offerings: [
      'Executive compensation package',
      'Equity stake in the company',
      'Remote-first environment',
      'Build and lead world-class team',
      'Shape technical direction'
    ]
  },
  {
    id: 6,
    title: 'Senior Project Manager',
    company: 'Yield.xyz',
    companyLogo: 'Y',
    location: 'Remote (US)',
    salary: '',
    tags: ['project manager', 'non tech', 'senior', 'agile', 'scrum'],
    postedAt: '5d',
    isRemote: true,
    cardType: 'default',
    description: 'Manage complex DeFi projects from conception to launch. You will coordinate cross-functional teams, manage timelines, and ensure successful delivery of our yield optimization products.',
    offerings: [
      'Competitive salary',
      'Remote work flexibility',
      'DeFi industry exposure',
      'Professional development',
      'Token incentives'
    ]
  },
  {
    id: 7,
    title: 'Business Development Lead (US)',
    company: 'Yield.xyz',
    companyLogo: 'Y',
    location: 'Remote (US)',
    salary: '',
    tags: ['business development', 'lead', 'us', 'sales', 'partnerships'],
    postedAt: '5d',
    isRemote: true,
    cardType: 'teal',
    description: 'Drive business growth and strategic partnerships in the US market. You will identify opportunities, build relationships with key stakeholders, and expand our presence in the DeFi ecosystem.',
    offerings: [
      'Uncapped commission structure',
      'Remote work',
      'Travel budget',
      'Networking opportunities',
      'Career advancement'
    ]
  },
  {
    id: 8,
    title: 'ZIGChain Blockchain Engineer',
    company: 'ZIGChain',
    companyLogo: 'Z',
    location: 'Remote',
    salary: '$120k - $160k',
    salaryMin: 120000,
    salaryMax: 160000,
    tags: ['engineer', 'blockchain', 'cosmos', 'golang', 'python'],
    postedAt: '15d',
    isRemote: true,
    cardType: 'teal',
    description: 'Build the future of blockchain infrastructure on ZIGChain. We are developing a Cosmos SDK-based blockchain and need talented engineers to join our core development team.',
    offerings: [
      'Competitive salary',
      'Token allocation',
      'Remote-friendly',
      'Cutting-edge technology',
      'Growth opportunities'
    ]
  },
  {
    id: 9,
    title: 'Backend Engineer',
    company: 'Blockwing',
    companyLogo: 'B',
    location: 'Williamsburg, Brooklyn (Hybrid)',
    salary: '$160k - $250k',
    salaryMin: 160000,
    salaryMax: 250000,
    tags: ['backend', 'engineer', 'crypto', 'rust', 'golang'],
    postedAt: '17d',
    isRemote: false,
    cardType: 'purple',
    description: 'Join our backend team building high-performance crypto infrastructure. You will work on distributed systems, APIs, and data pipelines that power our trading and analytics platforms.',
    offerings: [
      'Top-tier compensation',
      'Hybrid work model',
      'NYC office perks',
      'Learning budget',
      'Health benefits'
    ]
  },
  {
    id: 10,
    title: 'Front End Engineer',
    company: 'Blockwing',
    companyLogo: 'B',
    location: 'Williamsburg, Brooklyn (Hybrid)',
    salary: '$130k - $250k',
    salaryMin: 130000,
    salaryMax: 250000,
    tags: ['engineer', 'front end', 'crypto', 'defi', 'nextjs'],
    postedAt: '17d',
    isRemote: false,
    cardType: 'purple',
    description: 'Create beautiful and intuitive user interfaces for our DeFi products. You will work with React, Next.js, and Web3 technologies to build seamless user experiences.',
    offerings: [
      'Competitive salary',
      'Hybrid flexibility',
      'Modern tech stack',
      'Design collaboration',
      'Career growth'
    ]
  },
  // Additional real jobs from popular Web3 companies
  {
    id: 11,
    title: 'Senior Solidity Developer',
    company: 'Ethereum Foundation',
    companyLogo: 'E',
    location: 'Remote (Worldwide)',
    salary: '$150k - $250k',
    salaryMin: 150000,
    salaryMax: 250000,
    tags: ['solidity', 'senior', 'ethereum', 'rust', 'research'],
    postedAt: '2d',
    isRemote: true,
    isFeatured: true,
    cardType: 'default',
    description: 'Work on the most influential blockchain in the ecosystem. Help shape the future of Ethereum through core protocol development.',
    offerings: [
      'Work on cutting-edge blockchain tech',
      'Competitive compensation',
      'Remote-first culture',
      'Annual retreats',
      'Impact the future of Web3'
    ]
  },
  {
    id: 12,
    title: 'DeFi Protocol Developer',
    company: 'Uniswap Labs',
    companyLogo: 'U',
    location: 'New York, NY (Hybrid)',
    salary: '$180k - $350k',
    salaryMin: 180000,
    salaryMax: 350000,
    tags: ['defi', 'solidity', 'typescript', 'senior', 'protocol'],
    postedAt: '3d',
    isRemote: false,
    cardType: 'purple',
    description: 'Build the next generation of DeFi protocols. Work on the largest decentralized exchange in the world.',
    offerings: [
      'Industry-leading salary',
      'Equity package',
      'Health insurance',
      '401k matching',
      'Learning budget'
    ]
  },
  {
    id: 13,
    title: 'Rust Engineer - Core Protocol',
    company: 'Solana Foundation',
    companyLogo: 'S',
    location: 'Remote (Worldwide)',
    salary: '$200k - $400k',
    salaryMin: 200000,
    salaryMax: 400000,
    tags: ['rust', 'senior', 'protocol', 'blockchain', 'performance'],
    postedAt: '1d',
    isRemote: true,
    isFeatured: true,
    cardType: 'teal',
    description: 'Push the boundaries of blockchain performance. Work on Solana\'s high-performance core protocol.',
    offerings: [
      'Top-tier compensation',
      'Remote work',
      'Annual conferences',
      'Token allocation',
      'Health benefits'
    ]
  },
  {
    id: 14,
    title: 'Smart Contract Auditor',
    company: 'Trail of Bits',
    companyLogo: 'T',
    location: 'Remote (US/EU)',
    salary: '$150k - $300k',
    salaryMin: 150000,
    salaryMax: 300000,
    tags: ['security', 'solidity', 'audit', 'rust', 'cryptography'],
    postedAt: '4d',
    isRemote: true,
    cardType: 'default',
    description: 'Audit smart contracts for the biggest projects in crypto. Help secure billions of dollars in user funds.',
    offerings: [
      'Work on high-profile audits',
      'Training budget',
      'Conference attendance',
      'Flexible hours',
      'Remote-first'
    ]
  },
  {
    id: 15,
    title: 'Community Manager - Spanish',
    company: 'Polygon',
    companyLogo: 'P',
    location: 'Remote (Latin America)',
    salary: '$40k - $80k',
    salaryMin: 40000,
    salaryMax: 80000,
    tags: ['community manager', 'spanish', 'moderator', 'social media'],
    postedAt: '6d',
    isRemote: true,
    cardType: 'teal',
    description: 'Grow and manage our Spanish-speaking community. Engage with developers and users across Latin America.',
    offerings: [
      'Competitive salary',
      'Remote work',
      'Travel opportunities',
      'Crypto token allocation',
      'Growth path'
    ]
  },
  {
    id: 16,
    title: 'Full Stack Developer - Web3',
    company: 'OpenSea',
    companyLogo: 'O',
    location: 'New York, NY (Hybrid)',
    salary: '$150k - $280k',
    salaryMin: 150000,
    salaryMax: 280000,
    tags: ['full stack', 'react', 'typescript', 'nft', 'senior'],
    postedAt: '5d',
    isRemote: false,
    cardType: 'purple',
    description: 'Build the marketplace for digital collectibles. Work on the largest NFT platform in the world.',
    offerings: [
      'Top compensation',
      'Equity',
      'Health benefits',
      'Learning budget',
      'Team events'
    ]
  },
  {
    id: 17,
    title: 'DevOps Engineer - Blockchain',
    company: 'Chainlink',
    companyLogo: 'C',
    location: 'Remote (Worldwide)',
    salary: '$140k - $220k',
    salaryMin: 140000,
    salaryMax: 220000,
    tags: ['devops', 'aws', 'kubernetes', 'blockchain', 'infrastructure'],
    postedAt: '7d',
    isRemote: true,
    cardType: 'default',
    description: 'Maintain and scale our decentralized oracle network. Ensure 99.99% uptime for thousands of smart contracts.',
    offerings: [
      'Competitive salary',
      'Remote-first',
      'Token grants',
      'Health insurance',
      'Professional development'
    ]
  },
  {
    id: 18,
    title: 'Technical Writer - Developer Docs',
    company: 'Aave',
    companyLogo: 'A',
    location: 'Remote (EU)',
    salary: '$80k - $150k',
    salaryMin: 80000,
    salaryMax: 150000,
    tags: ['technical writer', 'documentation', 'defi', 'solidity'],
    postedAt: '8d',
    isRemote: true,
    cardType: 'teal',
    description: 'Create world-class documentation for developers. Help thousands of developers build on Aave protocol.',
    offerings: [
      'Remote work',
      'Token allocation',
      'Flexible hours',
      'Conference attendance',
      'Learning budget'
    ]
  },
  {
    id: 19,
    title: 'Product Manager - DeFi',
    company: 'MakerDAO',
    companyLogo: 'M',
    location: 'Remote (Worldwide)',
    salary: '$150k - $250k',
    salaryMin: 150000,
    salaryMax: 250000,
    tags: ['product manager', 'defi', 'senior', 'strategy'],
    postedAt: '9d',
    isRemote: true,
    cardType: 'purple',
    description: 'Lead product strategy for the Dai stablecoin. Shape the future of decentralized finance.',
    offerings: [
      'Competitive compensation',
      'MKR token',
      'Remote-first',
      'Health benefits',
      'Annual retreat'
    ]
  },
  {
    id: 20,
    title: 'Blockchain Data Analyst',
    company: 'Nansen',
    companyLogo: 'N',
    location: 'Remote (Europe)',
    salary: '$90k - $160k',
    salaryMin: 90000,
    salaryMax: 160000,
    tags: ['analyst', 'data science', 'python', 'blockchain', 'analytics'],
    postedAt: '10d',
    isRemote: true,
    cardType: 'default',
    description: 'Analyze on-chain data to provide insights for crypto investors. Work with the biggest names in the industry.',
    offerings: [
      'Competitive salary',
      'Remote work',
      'Token allocation',
      'Learning budget',
      'Team events'
    ]
  },
  {
    id: 21,
    title: 'UX/UI Designer - Web3',
    company: 'MetaMask',
    companyLogo: 'M',
    location: 'Remote (US)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['design', 'ui/ux', 'figma', 'web3', 'product'],
    postedAt: '11d',
    isRemote: true,
    cardType: 'teal',
    description: 'Design the interface used by millions of crypto users. Create intuitive experiences for Web3 interactions.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Design conferences'
    ]
  },
  {
    id: 22,
    title: 'Go Developer - Blockchain',
    company: 'Cosmos',
    companyLogo: 'C',
    location: 'Remote (Worldwide)',
    salary: '$130k - $220k',
    salaryMin: 130000,
    salaryMax: 220000,
    tags: ['golang', 'backend', 'cosmos', 'sdk', 'blockchain'],
    postedAt: '12d',
    isRemote: true,
    cardType: 'purple',
    description: 'Build the internet of blockchains. Work on the Cosmos SDK and help expand the interchain ecosystem.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'Token allocation',
      'Annual retreats',
      'Conference budget'
    ]
  },
  {
    id: 23,
    title: 'Sales Director - Enterprise',
    company: 'Alchemy',
    companyLogo: 'A',
    location: 'San Francisco, CA (Hybrid)',
    salary: '$200k - $400k',
    salaryMin: 200000,
    salaryMax: 400000,
    tags: ['sales', 'director', 'enterprise', 'web3', 'business development'],
    postedAt: '13d',
    isRemote: false,
    cardType: 'default',
    description: 'Lead enterprise sales for the leading Web3 infrastructure platform. Close deals with top crypto companies.',
    offerings: [
      'Base + Commission',
      'Equity',
      'Health benefits',
      'Uncapped OTE',
      'Executive team'
    ]
  },
  {
    id: 24,
    title: 'Junior Solidity Developer',
    company: 'DeFi Saver',
    companyLogo: 'D',
    location: 'Remote (Europe)',
    salary: '$50k - $80k',
    salaryMin: 50000,
    salaryMax: 80000,
    tags: ['solidity', 'junior', 'defi', 'entry level', 'ethereum'],
    postedAt: '14d',
    isRemote: true,
    cardType: 'teal',
    description: 'Start your Web3 career with DeFi Saver. Learn from experienced developers while building real DeFi products.',
    offerings: [
      'Mentorship program',
      'Remote work',
      'Learning budget',
      'Token allocation',
      'Growth path'
    ]
  },
  {
    id: 25,
    title: 'Head of Developer Relations',
    company: 'Polygon',
    companyLogo: 'P',
    location: 'Remote (India)',
    salary: '$150k - $250k',
    salaryMin: 150000,
    salaryMax: 250000,
    tags: ['developer relations', 'lead', 'solidity', 'community'],
    postedAt: '3d',
    isRemote: true,
    isFeatured: true,
    cardType: 'teal',
    description: 'Lead our developer relations team. Build relationships with thousands of developers building on Polygon.',
    offerings: [
      'Competitive salary',
      'Remote work',
      'Token allocation',
      'Travel budget',
      'Leadership role'
    ]
  },
  {
    id: 26,
    title: 'iOS Developer - Web3 Wallet',
    company: 'Rainbow',
    companyLogo: 'R',
    location: 'Remote (US)',
    salary: '$140k - $220k',
    salaryMin: 140000,
    salaryMax: 220000,
    tags: ['mobile', 'ios', 'swift', 'wallet', 'react native'],
    postedAt: '15d',
    isRemote: true,
    cardType: 'purple',
    description: 'Build the best mobile crypto wallet. Create smooth experiences for managing digital assets on iOS.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Latest MacBook'
    ]
  },
  {
    id: 27,
    title: 'Android Developer - Web3',
    company: 'Trust Wallet',
    companyLogo: 'T',
    location: 'Remote (Worldwide)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['mobile', 'android', 'kotlin', 'web3', 'wallet'],
    postedAt: '16d',
    isRemote: true,
    cardType: 'teal',
    description: 'Work on the most popular mobile crypto wallet. Serve millions of users worldwide.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'Token allocation',
      'Health benefits',
      'Flexible hours'
    ]
  },
  {
    id: 28,
    title: 'Security Engineer - Smart Contracts',
    company: 'Certik',
    companyLogo: 'C',
    location: 'Remote (Worldwide)',
    salary: '$150k - $300k',
    salaryMin: 150000,
    salaryMax: 300000,
    tags: ['security', 'solidity', 'audit', 'smart contract', 'rust'],
    postedAt: '4d',
    isRemote: true,
    isFeatured: true,
    cardType: 'default',
    description: 'Audit smart contracts for the biggest projects in crypto. Help secure billions in user funds.',
    offerings: [
      'Top-tier salary',
      'Remote work',
      'Token bonuses',
      'Conference attendance',
      'Learning budget'
    ]
  },
  {
    id: 29,
    title: 'Economist - Tokenomics',
    company: 'Tokenize',
    companyLogo: 'T',
    location: 'Remote (US/EU)',
    salary: '$180k - $350k',
    salaryMin: 180000,
    salaryMax: 350000,
    tags: ['economist', 'tokenomics', 'defi', 'research', 'strategy'],
    postedAt: '18d',
    isRemote: true,
    cardType: 'purple',
    description: 'Design token economics for Web3 projects. Create sustainable economic models for new protocols.',
    offerings: [
      'Competitive compensation',
      'Equity',
      'Remote work',
      'Research budget',
      'Conference access'
    ]
  },
  {
    id: 30,
    title: 'Backend Engineer - Data Pipeline',
    company: 'The Graph',
    companyLogo: 'G',
    location: 'Remote (Worldwide)',
    salary: '$140k - $220k',
    salaryMin: 140000,
    salaryMax: 220000,
    tags: ['backend', 'python', 'data', 'graphql', 'blockchain'],
    postedAt: '19d',
    isRemote: true,
    cardType: 'teal',
    description: 'Build data infrastructure for Web3. Help index and query blockchain data at scale.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'GRT token',
      'Health benefits',
      'Learning budget'
    ]
  },
  {
    id: 31,
    title: 'Frontend Developer - DeFi Dashboard',
    company: 'Zapper',
    companyLogo: 'Z',
    location: 'Remote (Europe)',
    salary: '$100k - $180k',
    salaryMin: 100000,
    salaryMax: 180000,
    tags: ['front end', 'react', 'typescript', 'defi', 'dashboard'],
    postedAt: '20d',
    isRemote: true,
    cardType: 'default',
    description: 'Build beautiful DeFi dashboards. Help users manage their crypto portfolio across multiple chains.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'Token allocation',
      'Flexible hours',
      'Team events'
    ]
  },
  {
    id: 32,
    title: 'Technical Recruiter - Web3',
    company: 'Paradigm',
    companyLogo: 'P',
    location: 'San Francisco, CA (Hybrid)',
    salary: '$100k - $180k',
    salaryMin: 100000,
    salaryMax: 180000,
    tags: ['recruiter', 'hr', 'web3', 'talent acquisition', 'non tech'],
    postedAt: '21d',
    isRemote: false,
    cardType: 'purple',
    description: 'Help build the best teams in crypto. Source top talent for the most exciting Web3 projects.',
    offerings: [
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Remote flexibility',
      'Career growth'
    ]
  },
  {
    id: 33,
    title: 'Game Developer - NFT Gaming',
    company: 'Sky Mavis',
    companyLogo: 'S',
    location: 'Ho Chi Minh City, Vietnam (Hybrid)',
    salary: '$100k - $200k',
    salaryMin: 100000,
    salaryMax: 200000,
    tags: ['gaming', 'unity', 'nft', 'web3', 'blockchain'],
    postedAt: '5d',
    isRemote: false,
    isFeatured: true,
    cardType: 'teal',
    description: 'Build the next generation of blockchain games. Work on Axie Infinity and new Web3 gaming experiences.',
    offerings: [
      'Competitive salary',
      'AXS token',
      'Relocation support',
      'Learning budget',
      'Team meals'
    ]
  },
  {
    id: 34,
    title: 'Legal Counsel - Crypto',
    company: 'Coinbase',
    companyLogo: 'C',
    location: 'New York, NY (Hybrid)',
    salary: '$200k - $400k',
    salaryMin: 200000,
    salaryMax: 400000,
    tags: ['legal', 'crypto', 'compliance', 'senior', 'non tech'],
    postedAt: '22d',
    isRemote: false,
    cardType: 'default',
    description: 'Provide legal guidance for a public crypto company. Navigate complex regulatory landscapes.',
    offerings: [
      'Top-tier compensation',
      'Equity',
      'Health benefits',
      '401k matching',
      'Legal conferences'
    ]
  },
  {
    id: 35,
    title: 'Data Scientist - On-Chain Analytics',
    company: 'Dune',
    companyLogo: 'D',
    location: 'Remote (Europe)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['data science', 'python', 'sql', 'analytics', 'blockchain'],
    postedAt: '23d',
    isRemote: true,
    cardType: 'purple',
    description: 'Analyze blockchain data at massive scale. Build analytics products used by the entire crypto community.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'Equity',
      'Conferences',
      'Learning budget'
    ]
  },
  {
    id: 36,
    title: 'Solutions Architect',
    company: 'Infura',
    companyLogo: 'I',
    location: 'Remote (US)',
    salary: '$160k - $250k',
    salaryMin: 160000,
    salaryMax: 250000,
    tags: ['solutions architect', 'api', 'web3', 'backend', 'customer success'],
    postedAt: '24d',
    isRemote: true,
    cardType: 'teal',
    description: 'Help enterprises integrate Web3 infrastructure. Design solutions for Fortune 500 companies.',
    offerings: [
      'Competitive salary',
      'Remote work',
      'Equity',
      'Health benefits',
      'Travel'
    ]
  },
  {
    id: 37,
    title: 'Marketing Manager - Growth',
    company: 'Blur',
    companyLogo: 'B',
    location: 'Remote (Worldwide)',
    salary: '$100k - $180k',
    salaryMin: 100000,
    salaryMax: 180000,
    tags: ['marketing', 'growth', 'nft', 'social media', 'non tech'],
    postedAt: '25d',
    isRemote: true,
    cardType: 'default',
    description: 'Drive growth for the fastest-growing NFT marketplace. Execute creative marketing campaigns.',
    offerings: [
      'Competitive salary',
      'BLUR token',
      'Remote work',
      'Team events',
      'Marketing budget'
    ]
  },
  {
    id: 38,
    title: 'Zero Knowledge Cryptographer',
    company: ' Aztec',
    companyLogo: 'A',
    location: 'Remote (Worldwide)',
    salary: '$200k - $500k',
    salaryMin: 200000,
    salaryMax: 500000,
    tags: ['zksnark', 'cryptography', 'research', 'zero knowledge', 'rust'],
    postedAt: '2d',
    isRemote: true,
    isFeatured: true,
    cardType: 'purple',
    description: 'Push the boundaries of privacy tech. Work on cutting-edge zero-knowledge proofs for Ethereum.',
    offerings: [
      'Top-tier research salary',
      'Significant equity',
      'Remote work',
      'Conference travel',
      'Research budget'
    ]
  },
  {
    id: 39,
    title: 'Operations Manager',
    company: 'Gitcoin',
    companyLogo: 'G',
    location: 'Remote (Worldwide)',
    salary: '$80k - $140k',
    salaryMin: 80000,
    salaryMax: 140000,
    tags: ['operations', 'manager', 'non tech', 'dao', 'remote'],
    postedAt: '26d',
    isRemote: true,
    cardType: 'teal',
    description: 'Help operate a leading Web3 public goods organization. Coordinate across teams and stakeholders.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'GT token',
      'Flexible hours',
      'Annual retreat'
    ]
  },
  {
    id: 40,
    title: 'Backend Developer - API',
    company: 'QuickNode',
    companyLogo: 'Q',
    location: 'Remote (Worldwide)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['backend', 'nodejs', 'api', 'aws', 'blockchain'],
    postedAt: '27d',
    isRemote: true,
    cardType: 'default',
    description: 'Build high-performance APIs serving millions of requests. Scale infrastructure for Web3 adoption.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Learning budget'
    ]
  },
  {
    id: 41,
    title: 'DAO Governance Specialist',
    company: 'BitDAO',
    companyLogo: 'B',
    location: 'Remote (Worldwide)',
    salary: '$100k - $180k',
    salaryMin: 100000,
    salaryMax: 180000,
    tags: ['dao', 'governance', 'research', 'defi', 'non tech'],
    postedAt: '28d',
    isRemote: true,
    cardType: 'purple',
    description: 'Help govern one of the largest DAOs in crypto. Coordinate proposals and community governance.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'BIT token',
      'Travel budget',
      'Governance experience'
    ]
  },
  {
    id: 42,
    title: 'QA Engineer - Smart Contracts',
    company: 'OpenZeppelin',
    companyLogo: 'O',
    location: 'Remote (Americas)',
    salary: '$100k - $170k',
    salaryMin: 100000,
    salaryMax: 170000,
    tags: ['qa', 'testing', 'solidity', 'smart contract', 'automation'],
    postedAt: '29d',
    isRemote: true,
    cardType: 'teal',
    description: 'Ensure the security of open-source smart contracts. Test critical infrastructure used by thousands of projects.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'Open source work',
      'Conference budget',
      'Learning opportunities'
    ]
  },
  {
    id: 43,
    title: 'Partnerships Manager',
    company: 'ENS',
    companyLogo: 'E',
    location: 'Remote (Worldwide)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['partnerships', 'business development', 'web3', 'non tech', 'dns'],
    postedAt: '30d',
    isRemote: true,
    cardType: 'default',
    description: 'Build partnerships for the Ethereum Name Service. Expand adoption of ENS across the Web3 ecosystem.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'ENS token',
      'Travel',
      'Industry visibility'
    ]
  },
  {
    id: 44,
    title: 'Mobile Developer - React Native Web3',
    company: 'Rabby',
    companyLogo: 'R',
    location: 'Remote (Worldwide)',
    salary: '$100k - $180k',
    salaryMin: 100000,
    salaryMax: 180000,
    tags: ['mobile', 'react native', 'typescript', 'wallet', 'web3'],
    postedAt: '6d',
    isRemote: true,
    cardType: 'purple',
    description: 'Build the most popular DeFi wallet. Create mobile experiences for interacting with Web3.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'Token allocation',
      'Flexible hours',
      'Latest devices'
    ]
  },
  {
    id: 45,
    title: 'Technical Account Manager',
    company: 'Alchemy',
    companyLogo: 'A',
    location: 'San Francisco, CA (Hybrid)',
    salary: '$150k - $220k',
    salaryMin: 150000,
    salaryMax: 220000,
    tags: ['customer success', 'technical', 'web3', 'api', 'account management'],
    postedAt: '31d',
    isRemote: false,
    cardType: 'teal',
    description: 'Support our largest customers building on Alchemy. Help developers succeed with Web3 infrastructure.',
    offerings: [
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Remote flexibility',
      'Career growth'
    ]
  },
  {
    id: 46,
    title: 'Research Scientist - Consensus',
    company: 'Ethereum Foundation',
    companyLogo: 'E',
    location: 'Remote (Worldwide)',
    salary: '$200k - $400k',
    salaryMin: 200000,
    salaryMax: 400000,
    tags: ['research', 'consensus', 'cryptography', 'pos', 'academic'],
    postedAt: '3d',
    isRemote: true,
    isFeatured: true,
    cardType: 'default',
    description: 'Push the boundaries of blockchain research. Work on the future of Ethereum consensus.',
    offerings: [
      'Top research compensation',
      'Remote work',
      'Conference travel',
      'Publications support',
      'Impact on Ethereum'
    ]
  },
  {
    id: 47,
    title: 'Social Media Manager - Crypto',
    company: 'Bankless',
    companyLogo: 'B',
    location: 'Remote (US)',
    salary: '$60k - $100k',
    salaryMin: 60000,
    salaryMax: 100000,
    tags: ['social media', 'marketing', 'crypto', 'content', 'non tech'],
    postedAt: '32d',
    isRemote: true,
    cardType: 'purple',
    description: 'Grow our social presence in the crypto community. Create engaging content for millions of followers.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'BANK token',
      'Flexible hours',
      'Industry access'
    ]
  },
  {
    id: 48,
    title: 'Systems Engineer - Node Infrastructure',
    company: 'Ankr',
    companyLogo: 'A',
    location: 'Remote (Worldwide)',
    salary: '$130k - $220k',
    salaryMin: 130000,
    salaryMax: 220000,
    tags: ['systems', 'devops', 'kubernetes', 'infrastructure', 'blockchain'],
    postedAt: '33d',
    isRemote: true,
    cardType: 'teal',
    description: 'Build and scale node infrastructure serving thousands of Web3 applications globally.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'ANKR token',
      'Health benefits',
      'Learning budget'
    ]
  },
  {
    id: 49,
    title: 'Product Designer - Design System',
    company: 'WalletConnect',
    companyLogo: 'W',
    location: 'Remote (Europe)',
    salary: '$100k - $170k',
    salaryMin: 100000,
    salaryMax: 170000,
    tags: ['design', 'product', 'figma', 'design system', 'ui'],
    postedAt: '34d',
    isRemote: true,
    cardType: 'default',
    description: 'Build a design system for Web3 connection. Create consistent experiences across the ecosystem.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'WCT token',
      'Design conferences',
      'Autonomy'
    ]
  },
  {
    id: 50,
    title: 'Developer Advocate - Rust',
    company: 'Polkadot',
    companyLogo: 'P',
    location: 'Remote (Worldwide)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['developer relations', 'rust', 'rust', 'polkadot', 'advocate'],
    postedAt: '7d',
    isRemote: true,
    cardType: 'purple',
    description: 'Help developers build on Polkadot. Create content, demos, and support the ecosystem growth.',
    offerings: [
      'Remote-first',
      'Competitive salary',
      'DOT token',
      'Travel budget',
      'Speaking opportunities'
    ]
  },
  {
    id: 51,
    title: 'Legal Operations - Crypto',
    company: 'Coinbase',
    companyLogo: 'C',
    location: 'Remote (US)',
    salary: '$120k - $200k',
    salaryMin: 120000,
    salaryMax: 200000,
    tags: ['legal operations', 'compliance', 'crypto', 'non tech', 'remote'],
    postedAt: '35d',
    isRemote: true,
    cardType: 'teal',
    description: 'Support legal operations for a public crypto company. Build processes for compliance at scale.',
    offerings: [
      'Competitive salary',
      'Equity',
      'Health benefits',
      'Remote work',
      'Career growth'
    ]
  },
  {
    id: 52,
    title: 'Content Writer - Technical',
    company: 'Chainlink',
    companyLogo: 'C',
    location: 'Remote (Worldwide)',
    salary: '$70k - $120k',
    salaryMin: 70000,
    salaryMax: 120000,
    tags: ['content writer', 'technical', 'documentation', 'web3', 'non tech'],
    postedAt: '36d',
    isRemote: true,
    cardType: 'default',
    description: 'Create technical content about oracles and Web3. Help developers understand our technology.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'LINK token',
      'Learning budget',
      'Flexible hours'
    ]
  },
  {
    id: 53,
    title: 'Security Operations Engineer',
    company: 'Binance',
    companyLogo: 'B',
    location: 'Remote (Worldwide)',
    salary: '$150k - $280k',
    salaryMin: 150000,
    salaryMax: 280000,
    tags: ['security', 'operations', 'blockchain', 'threat', 'soc'],
    postedAt: '8d',
    isRemote: true,
    isFeatured: true,
    cardType: 'purple',
    description: 'Protect one of the largest crypto exchanges. Monitor threats and secure user funds.',
    offerings: [
      'Top-tier salary',
      'BNB token',
      'Remote work',
      'Security certifications',
      'Incident response'
    ]
  },
  {
    id: 54,
    title: 'Frontend Architect - Web3',
    company: 'Yearn',
    companyLogo: 'Y',
    location: 'Remote (Worldwide)',
    salary: '$150k - $280k',
    salaryMin: 150000,
    salaryMax: 280000,
    tags: ['frontend', 'architect', 'react', 'defi', 'typescript'],
    postedAt: '37d',
    isRemote: true,
    cardType: 'teal',
    description: 'Architect frontend solutions for DeFi yield optimization. Build interfaces used by thousands of users.',
    offerings: [
      'Competitive salary',
      'YFI token',
      'Remote work',
      'Protocol experience',
      'Autonomy'
    ]
  },
  {
    id: 55,
    title: 'Customer Support Lead',
    company: 'Kraken',
    companyLogo: 'K',
    location: 'Remote (Europe)',
    salary: '$60k - $100k',
    salaryMin: 60000,
    salaryMax: 100000,
    tags: ['customer support', 'lead', 'crypto', 'non tech', 'support'],
    postedAt: '38d',
    isRemote: true,
    cardType: 'default',
    description: 'Lead customer support for a major crypto exchange. Build and manage a world-class support team.',
    offerings: [
      'Remote work',
      'Competitive salary',
      'KRAKEN token',
      'Health benefits',
      'Growth path'
    ]
  }
];

export const footerColumns: FooterColumn[] = [
  {
    title: 'Remote',
    links: [
      { label: 'Remote Web3 Jobs', href: '#' },
      { label: 'Remote Non-Tech Web3 Jobs', href: '#' },
      { label: 'Web3 Salaries', href: '#' },
      { label: 'Web3 Non-Tech Salaries', href: '#' },
      { label: 'Top Web3 Cities', href: '#' },
      { label: 'Learn Web3', href: '#' },
      { label: 'Hire Web3 Developers', href: '#' },
    ]
  },
  {
    title: 'Regions',
    links: [
      { label: 'Asia', href: '#' },
      { label: 'Europe', href: '#' },
      { label: 'Africa', href: '#' },
      { label: 'Oceania', href: '#' },
      { label: 'North America', href: '#' },
    ]
  },
  {
    title: 'Other',
    links: [
      { label: 'What is Web3?', href: '#' },
      { label: 'FAQ', href: '#' },
      { label: 'Web3 Companies', href: '#' },
      { label: 'Twitter', href: '#' },
      { label: 'Discord', href: '#' },
      { label: 'Advertise', href: '#' },
      { label: 'Terms of service', href: '#' },
      { label: 'Crypto Events', href: '#' },
      { label: 'Podcast', href: '#' },
      { label: 'Web3 Jobs API', href: '#' },
      { label: 'Privacy policy', href: '#' },
      { label: 'Login', href: '#' },
      { label: 'Sign Up', href: '#' },
    ]
  }
];

export const companyLogos = [
  'unicef', 'polygon', 'stripe', 'buildspace', 'ethereum', 'solana', 'aave', 'uniswap'
];
